version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@uploadcare/file-uploader"
      - dependency-name: "@uploadcare/react-uploader"
    versioning-strategy: increase
    assignees:
      - egordidenko
      - nd0ut
